In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/enriched_dataset.csv")

df.head()

,video_id,title,published_date,year,month,title_length,transcript
0,UsfpzxZNsPo,Python Essentials for AI Agents – Tutorial,2026-02-25 11:00:52+00:00,2026,2,42,Welcome to this Python essentials for building...
1,U6-RekkuORI,Closures in JavaScript explained with a simple...,2026-02-24 13:05:28+00:00,2026,2,63,What are closures and how would you describe t...
2,bB5eA7vU9W8,Learn Notion – Full Course for Beginners,2026-02-24 11:00:57+00:00,2026,2,40,Welcome to this comprehensive guide to masteri...
3,Ai00MsNabaE,True or false: computers only understand 1s an...,2026-02-23 13:17:29+00:00,2026,2,54,True or false? Computers only understand ones ...
4,QMgIovzpYVw,"When you're working, work hard. And when you r...",2026-02-22 13:43:36+00:00,2026,2,63,Having that sort of approach to your life migh...

In [3]:
print("Dataset shape:", df.shape)

print("\nColumns:")
print(df.columns)

print("\nMissing transcripts:", df["transcript"].isna().sum())

Dataset shape: (300, 7)

Columns:
Index(['video_id', 'title', 'published_date', 'year', 'month', 'title_length',
       'transcript'],
      dtype='str')

Missing transcripts: 5

In [4]:
import re

def clean_text(text):
    if pd.isna(text):
        return text
    
    # remove newline and tab characters
    text = re.sub(r'\n', ' ', text)
    text = re.sub(r'\t', ' ', text)
    
    # remove special characters
    text = re.sub(r'#|@|\*', '', text)
    
    # remove multiple spaces
    text = re.sub(r'\s+', ' ', text)

    return text.strip()

# apply cleaning
df["title"] = df["title"].apply(clean_text)
df["transcript"] = df["transcript"].apply(clean_text)

df.head()

,video_id,title,published_date,year,month,title_length,transcript
0,UsfpzxZNsPo,Python Essentials for AI Agents – Tutorial,2026-02-25 11:00:52+00:00,2026,2,42,Welcome to this Python essentials for building...
1,U6-RekkuORI,Closures in JavaScript explained with a simple...,2026-02-24 13:05:28+00:00,2026,2,63,What are closures and how would you describe t...
2,bB5eA7vU9W8,Learn Notion – Full Course for Beginners,2026-02-24 11:00:57+00:00,2026,2,40,Welcome to this comprehensive guide to masteri...
3,Ai00MsNabaE,True or false: computers only understand 1s an...,2026-02-23 13:17:29+00:00,2026,2,54,True or false? Computers only understand ones ...
4,QMgIovzpYVw,"When you're working, work hard. And when you r...",2026-02-22 13:43:36+00:00,2026,2,63,Having that sort of approach to your life migh...

In [5]:
df = df.dropna(subset=["transcript"])

print("Remaining rows:", len(df))

Remaining rows: 295

For semantic search we only need:

video_id
title
published_date
transcript

In [6]:
df = df[["video_id", "title", "published_date", "transcript"]]

df.head()

,video_id,title,published_date,transcript
0,UsfpzxZNsPo,Python Essentials for AI Agents – Tutorial,2026-02-25 11:00:52+00:00,Welcome to this Python essentials for building...
1,U6-RekkuORI,Closures in JavaScript explained with a simple...,2026-02-24 13:05:28+00:00,What are closures and how would you describe t...
2,bB5eA7vU9W8,Learn Notion – Full Course for Beginners,2026-02-24 11:00:57+00:00,Welcome to this comprehensive guide to masteri...
3,Ai00MsNabaE,True or false: computers only understand 1s an...,2026-02-23 13:17:29+00:00,True or false? Computers only understand ones ...
4,QMgIovzpYVw,"When you're working, work hard. And when you r...",2026-02-22 13:43:36+00:00,Having that sort of approach to your life migh...

In [7]:
df.to_csv("../data/cleaned_transcripts.csv", index=False)

print("Cleaned transcripts dataset saved successfully!")

Cleaned transcripts dataset saved successfully!

Step 5 : Create Queries List

In [25]:
queries = [
"What is Python programming?",
"Python for beginners tutorial",
"How to use lists in Python?",
"How do Python dictionaries work?",
"What are Python functions?",
"What are Python classes and objects?",
"What is object oriented programming in Python?",
"How to work with strings in Python?",
"What is list comprehension in Python?",
"How to debug Python code?",

"What is JavaScript?",
"JavaScript for beginners tutorial",
"What are JavaScript closures?",
"What is the JavaScript event loop?",
"What are promises in JavaScript?",
"What is async await in JavaScript?",
"What are JavaScript arrays?",
"What are arrow functions in JavaScript?",
"What is DOM manipulation in JavaScript?",
"How does JavaScript handle callbacks?",

"What is HTML?",
"HTML full course for beginners",
"What are HTML semantic tags?",
"How to create forms in HTML?",
"What are HTML attributes?",
"What is CSS?",
"CSS flexbox explained",
"What is CSS grid?",
"How to center elements using CSS?",
"Responsive web design tutorial",

"What is React JS?",
"React tutorial for beginners",
"What are React components?",
"What are React hooks?",
"What is useState in React?",
"What is useEffect in React?",
"How does React handle state?",
"What is Next.js?",
"What is Node.js?",
"What is Express.js?",

"What is machine learning?",
"Machine learning for beginners",
"What is supervised learning?",
"What is unsupervised learning?",
"What is deep learning?",
"What are neural networks?",
"What is gradient descent?",
"What is overfitting in machine learning?",
"What is underfitting in machine learning?",
"What is model training?",

"What is artificial intelligence?",
"What are AI agents?",
"What is natural language processing?",
"What are embeddings in AI?",
"What is semantic search?",
"What is cosine similarity?",
"What are transformer models?",
"What are sentence transformers?",
"What is HuggingFace?",

"What is data science?",
"What is pandas in Python?",
"What is NumPy used for?",
"What is scikit-learn?",
"What is data preprocessing?",
"What is exploratory data analysis?",
"What is data visualization in Python?",
"What is a dataset?",
"What is feature engineering?",
"What is model evaluation?"
]

In [26]:
queries_df = pd.DataFrame(queries, columns=["query"])

queries_df.head()

                              query
0       What is Python programming?
1     Python for beginners tutorial
2       How to use lists in Python?
3  How do Python dictionaries work?
4        What are Python functions?

In [27]:
queries_df = pd.DataFrame(queries, columns=["query"])
queries_df.to_csv("../data/search_queries.csv", index=False)

print("Total queries:", len(queries))

Total queries: 69

Step 6: Map Queries to Relevant Videos

In [28]:
queries_df = pd.read_csv("../data/search_queries.csv")
videos_df = pd.read_csv("../data/cleaned_transcripts.csv")

print("Queries:", len(queries_df))
print("Videos:", len(videos_df))

Queries: 69
Videos: 295

In [29]:
query_video_mapping = pd.DataFrame({
    "query": queries_df["query"],
    "relevant_video_id": videos_df["video_id"].head(len(queries_df))
})

query_video_mapping.head()

                              query relevant_video_id
0       What is Python programming?       UsfpzxZNsPo
1     Python for beginners tutorial       U6-RekkuORI
2       How to use lists in Python?       bB5eA7vU9W8
3  How do Python dictionaries work?       Ai00MsNabaE
4        What are Python functions?       QMgIovzpYVw

In [30]:
query_video_mapping.to_csv("../data/query_video_mapping.csv", index=False)

print("Query-video mapping saved!")

Query-video mapping saved!

Step 7: Study Sentence Transformers

In [15]:
!pip install sentence-transformers

Collecting sentence-transformers
  Using cached sentence_transformers-5.2.3-py3-none-any.whl.metadata (16 kB)
Collecting transformers<6.0.0,>=4.41.0 (from sentence-transformers)
  Downloading transformers-5.3.0-py3-none-any.whl.metadata (32 kB)
Collecting huggingface-hub>=0.20.0 (from sentence-transformers)
  Downloading huggingface_hub-1.6.0-py3-none-any.whl.metadata (13 kB)
Collecting torch>=1.11.0 (from sentence-transformers)
  Using cached torch-2.10.0-cp312-cp312-win_amd64.whl.metadata (31 kB)
Requirement already satisfied: numpy in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from sentence-transformers) (2.4.2)
Collecting scikit-learn (from sentence-transformers)
  Using cached scikit_learn-1.8.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Collecting scipy (from sentence-transformers)
  Using cached scipy-1.17.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from sentence-transformers) (4.15.0)
Collecting tqdm (from sentence-transformers)
  Using cached tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Collecting filelock>=3.10.0 (from huggingface-hub>=0.20.0->sentence-transformers)
  Downloading filelock-3.25.2-py3-none-any.whl.metadata (2.0 kB)
Collecting fsspec>=2023.5.0 (from huggingface-hub>=0.20.0->sentence-transformers)
  Using cached fsspec-2026.2.0-py3-none-any.whl.metadata (10 kB)
Collecting hf-xet<2.0.0,>=1.3.2 (from huggingface-hub>=0.20.0->sentence-transformers)
  Downloading hf_xet-1.4.0-cp37-abi3-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.3)
Collecting typer (from huggingface-hub>=0.20.0->sentence-transformers)
  Using cached typer-0.24.1-py3-none-any.whl.metadata (16 kB)
Collecting sympy>=1.13.3 (from torch>=1.11.0->sentence-transformers)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch>=1.11.0->sentence-transformers)
  Using cached networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: jinja2 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: setuptools in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from torch>=1.11.0->sentence-transformers) (82.0.0)
Requirement already satisfied: colorama in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from tqdm->sentence-transformers) (0.4.6)
Collecting regex!=2019.12.17 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading regex-2026.2.28-cp312-cp312-win_amd64.whl.metadata (41 kB)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl.metadata (7.4 kB)
Collecting safetensors>=0.4.3 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Using cached safetensors-0.7.0-cp38-abi3-win_amd64.whl.metadata (4.2 kB)
Collecting joblib>=1.3.0 (from scikit-learn->sentence-transformers)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn->sentence-transformers)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: anyio in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.12.1)
Requirement already satisfied: certifi in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Collecting click>=8.2.1 (from typer->huggingface-hub>=0.20.0->sentence-transformers)
  Using cached click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
Collecting shellingham>=1.3.0 (from typer->huggingface-hub>=0.20.0->sentence-transformers)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=12.3.0 (from typer->huggingface-hub>=0.20.0->sentence-transformers)
  Using cached rich-14.3.3-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer->huggingface-hub>=0.20.0->sentence-transformers)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers)
  Using cached markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (2.19.2)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Using cached sentence_transformers-5.2.3-py3-none-any.whl (494 kB)
Downloading huggingface_hub-1.6.0-py3-none-any.whl (612 kB)
   ---------------------------------------- 0.0/612.9 kB ? eta -:--:--
   ---------------------------------------- 612.9/612.9 kB 5.6 MB/s eta 0:00:00
Using cached torch-2.10.0-cp312-cp312-win_amd64.whl (113.8 MB)
Using cached tqdm-4.67.3-py3-none-any.whl (78 kB)
Downloading transformers-5.3.0-py3-none-any.whl (10.7 MB)
   ---------------------------------------- 0.0/10.7 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/10.7 MB 7.4 MB/s eta 0:00:02
   ---------- ----------------------------- 2.9/10.7 MB 7.6 MB/s eta 0:00:02
   ----------------- ---------------------- 4.7/10.7 MB 8.4 MB/s eta 0:00:01
   ------------------------ --------------- 6.6/10.7 MB 8.4 MB/s eta 0:00:01
   ------------------------------ --------- 8.1/10.7 MB 8.5 MB/s eta 0:00:01
   ------------------------------------ --- 9.7/10.7 MB 8.5 MB/s eta 0:00:01
   ---------------------------------------- 10.7/10.7 MB 8.2 MB/s eta 0:00:00
Using cached scikit_learn-1.8.0-cp312-cp312-win_amd64.whl (8.0 MB)
Using cached scipy-1.17.1-cp312-cp312-win_amd64.whl (36.5 MB)
Downloading filelock-3.25.2-py3-none-any.whl (26 kB)
Using cached fsspec-2026.2.0-py3-none-any.whl (202 kB)
Downloading hf_xet-1.4.0-cp37-abi3-win_amd64.whl (3.7 MB)
   ---------------------------------------- 0.0/3.7 MB ? eta -:--:--
   -------------- ------------------------- 1.3/3.7 MB 7.4 MB/s eta 0:00:01
   ---------------------------- ----------- 2.6/3.7 MB 6.9 MB/s eta 0:00:01
   ---------------------------------------- 3.7/3.7 MB 6.6 MB/s eta 0:00:00
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached networkx-3.6.1-py3-none-any.whl (2.1 MB)
Downloading regex-2026.2.28-cp312-cp312-win_amd64.whl (277 kB)
Using cached safetensors-0.7.0-cp38-abi3-win_amd64.whl (341 kB)
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl (2.7 MB)
Using cached typer-0.24.1-py3-none-any.whl (56 kB)
Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Using cached click-8.3.1-py3-none-any.whl (108 kB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Using cached rich-14.3.3-py3-none-any.whl (310 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Using cached markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: mpmath, tqdm, threadpoolctl, sympy, shellingham, scipy, safetensors, regex, networkx, mdurl, joblib, hf-xet, fsspec, filelock, click, annotated-doc, torch, scikit-learn, markdown-it-py, rich, typer, huggingface-hub, tokenizers, transformers, sentence-transformers

ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\ramsa\\OneDrive\\Desktop\\QueryTubeAI_Web\\venv\\Lib\\site-packages\\transformers\\models\\t5gemma2\\configuration_t5gemma2.py'
Check the permissions.


[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting sentence-transformers
  Using cached sentence_transformers-5.2.3-py3-none-any.whl.metadata (16 kB)
Collecting transformers<6.0.0,>=4.41.0 (from sentence-transformers)
  Using cached transformers-5.3.0-py3-none-any.whl.metadata (32 kB)
Collecting huggingface-hub>=0.20.0 (from sentence-transformers)
  Using cached huggingface_hub-1.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: torch>=1.11.0 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from sentence-transformers) (2.10.0)
Requirement already satisfied: numpy in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from sentence-transformers) (2.4.2)
Collecting scikit-learn (from sentence-transformers)
  Using cached scikit_learn-1.8.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: scipy in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from sentence-transformers) (1.17.1)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.3.2 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.4.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.3)
Collecting typer (from huggingface-hub>=0.20.0->sentence-transformers)
  Using cached typer-0.24.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: sympy>=1.13.3 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: setuptools in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from torch>=1.11.0->sentence-transformers) (82.0.0)
Requirement already satisfied: colorama in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from tqdm->sentence-transformers) (0.4.6)
Requirement already satisfied: regex!=2019.12.17 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.2.28)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl.metadata (7.4 kB)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: joblib>=1.3.0 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: anyio in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.12.1)
Requirement already satisfied: certifi in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (1.5.4)
Collecting rich>=12.3.0 (from typer->huggingface-hub>=0.20.0->sentence-transformers)
  Using cached rich-14.3.3-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (0.0.4)
Collecting markdown-it-py>=2.2.0 (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers)
  Using cached markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\ramsa\onedrive\desktop\querytubeai_web\venv\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (0.1.2)
Using cached sentence_transformers-5.2.3-py3-none-any.whl (494 kB)
Using cached huggingface_hub-1.6.0-py3-none-any.whl (612 kB)
Using cached transformers-5.3.0-py3-none-any.whl (10.7 MB)
Using cached scikit_learn-1.8.0-cp312-cp312-win_amd64.whl (8.0 MB)
Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl (2.7 MB)
Using cached typer-0.24.1-py3-none-any.whl (56 kB)
Using cached rich-14.3.3-py3-none-any.whl (310 kB)
Using cached markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
Installing collected packages: markdown-it-py, scikit-learn, rich, typer, huggingface-hub, tokenizers, transformers, sentence-transformers
Successfully installed huggingface-hub-1.6.0 markdown-it-py-4.0.0 rich-14.3.3 scikit-learn-1.8.0 sentence-transformers-5.2.3 tokenizers-0.22.2 transformers-5.3.0 typer-0.24.1

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [31]:
from sentence_transformers import SentenceTransformer

In [32]:
model = SentenceTransformer("all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [33]:
sentences = [
    "What is Python?",
    "Python is a programming language"
]

embeddings = model.encode(sentences)

print("Embedding shape:", embeddings.shape)

Embedding shape: (2, 384)

In [34]:
transcripts = df["transcript"].tolist()

transcript_embeddings = model.encode(transcripts, show_progress_bar=True)

print("Number of transcripts:", len(transcript_embeddings))
print("Embedding size:", transcript_embeddings[0].shape)

Batches:   0%|          | 0/10 [00:00<?, ?it/s]

Number of transcripts: 295
Embedding size: (384,)

In [35]:
import numpy as np

np.save("../data/transcript_embeddings.npy", transcript_embeddings)

print("Transcript embeddings saved!")

Transcript embeddings saved!

How to open the .npy file

In [21]:
import numpy as np

embeddings = np.load("../data/transcript_embeddings.npy")

print("Shape:", embeddings.shape)

Shape: (295, 384)

In [22]:
# View the first embedding
print(embeddings[0])

[-2.31843907e-03 -5.19820787e-02 -7.05091134e-02  4.48069312e-02
 -4.66038883e-02 -1.13634482e-01  6.02296479e-02  4.20171469e-02
 -1.03461578e-01  7.90906511e-03  4.90065711e-03  1.57319605e-02
  9.34843048e-02 -2.84694191e-02  6.08873144e-02  6.97836056e-02
  1.48246728e-03 -3.03489435e-02 -4.93518114e-02 -1.00058168e-01
 -7.96049275e-03  2.58298814e-02  4.46250327e-02 -3.51539673e-03
 -5.69496863e-02  4.20361049e-02  6.06175736e-02 -1.84275080e-02
 -3.61453220e-02 -3.08107305e-02 -1.67593465e-03 -5.17572500e-02
  6.81075454e-03  6.00176677e-02  1.01624895e-02  5.42852702e-03
 -1.41930347e-02 -8.28578547e-02  1.20098125e-02  1.42291253e-02
 -5.62214032e-02 -3.45514156e-02 -7.01667219e-02 -5.33945821e-02
  2.75441306e-03  1.96209308e-02 -6.26872927e-02 -2.43824814e-03
  4.83400486e-02  2.36169621e-03 -1.43957824e-01 -3.36481854e-02
 -3.92743871e-02 -1.78477284e-03 -1.80053059e-02  2.05344893e-02
  2.87156049e-02 -1.84995439e-02  9.99637041e-03 -1.19369172e-01
 -8.25367682e-03 -2.99786869e-02  3.40482406e-02  7.90276192e-03
 -6.20698780e-02 -4.31670621e-02 -7.36313462e-02  8.00369084e-02
  1.13280550e-01 -8.01962987e-02 -6.03436045e-02 -1.35417236e-02
 -2.79167090e-02  5.53279296e-02  3.62557843e-02 -7.37855360e-02
  1.31945862e-02 -2.04852391e-02  6.50174394e-02 -1.40390405e-02
 -5.28320484e-02 -2.01532971e-02 -1.30612524e-02  1.22533098e-01
 -7.93392584e-03 -7.73450807e-02  8.46333802e-02  1.23422831e-01
  5.85440430e-04  1.22928908e-02  1.18678980e-01 -4.02324535e-02
  8.41112286e-02  2.39665378e-02  9.91041064e-02  8.30508247e-02
 -1.93234216e-02 -1.02332495e-01  1.46990661e-02  2.41514761e-02
 -3.82457078e-02 -4.02314775e-03 -6.68576285e-02 -6.08580885e-03
 -8.13340098e-02  4.01451997e-02  2.37197280e-02 -5.59924431e-02
  1.46001363e-02 -5.70765063e-02 -2.16834582e-02 -3.30544300e-02
 -4.04706970e-02 -3.79522033e-02  3.41978818e-02  2.77262293e-02
 -2.51892600e-02  5.64916134e-02  8.36516265e-03  2.88666040e-02
 -2.27498659e-03  3.55385207e-02 -4.89083193e-02  3.67098302e-02
  9.82286707e-02 -2.15467308e-02 -6.48195809e-03 -3.75897793e-34
 -1.56019637e-02  4.17369120e-02 -3.96005949e-03  9.44508389e-02
  5.92029616e-02 -3.71802598e-02  6.97587505e-02  5.51890954e-02
 -9.77949649e-02  8.03741589e-02  2.74131391e-02  8.36424381e-02
 -6.32713139e-02  2.53313277e-02  1.18013099e-02 -6.46465495e-02
  1.50504010e-03  1.48860672e-02  2.50220369e-03  1.85265504e-02
  3.09029147e-02  2.03585196e-02  5.17003909e-02  7.43032396e-02
  6.80798963e-02  2.26114634e-02 -1.32725965e-02 -1.78212561e-02
  5.81559241e-02 -1.10522006e-02 -8.05522949e-02  1.24631710e-02
 -7.07435235e-02  6.18836172e-02 -2.67426670e-02 -7.23182550e-03
 -6.88335896e-02 -3.51400115e-02 -5.45453280e-03  5.23219295e-02
 -3.74509729e-02  5.19634113e-02  3.68470512e-02 -6.10839501e-02
 -4.89702113e-02  5.63047752e-02  1.35254106e-02  8.04667082e-03
  3.87038216e-02 -2.41032615e-03 -4.12058346e-02 -5.82295507e-02
  2.49274913e-02  7.12751225e-02 -6.88899588e-03  9.04524773e-02
  5.44216298e-03 -3.88588235e-02 -1.30730150e-02 -2.97587160e-02
  9.16610472e-03 -4.40850556e-02  2.18257047e-02  3.64656188e-02
  9.74268094e-03  3.28044849e-03  3.06264460e-02  9.51363593e-02
  1.22083694e-01 -4.98143472e-02 -2.02240478e-02  5.15836142e-02
  2.57901326e-02 -1.13019850e-02 -1.38685778e-02  4.83537577e-02
  4.71476540e-02 -1.23539463e-01 -1.84393637e-02  3.34566236e-02
  1.05853134e-03  1.15159759e-02  3.04421484e-02 -2.28794981e-02
 -2.41099652e-02  4.30028606e-03 -3.14045921e-02 -1.12007605e-02
  6.89995289e-03  1.97710842e-02 -5.26689552e-02  4.01229656e-04
 -6.91683069e-02  2.45846212e-02 -4.76865517e-03 -2.85985121e-33
  4.77431491e-02 -3.99092271e-04 -7.02578574e-02 -7.12963147e-03
  1.56428013e-02 -2.47658733e-02 -3.81505191e-02 -6.02285517e-03
  6.39161170e-02 -6.83963671e-02 -7.29886442e-02 -3.24489176e-02
  4.23684493e-02 -1.04074730e-02 -2.46332902e-02  1.30303111e-03
 -2.36539245e-02 -4.50646393e-02 -8.05311650e-03  3.57328020e-02
 -8.56174752e-02  7.87337720e-02 -9.56740677e-02 -8.41188654e-02
 -1.93384048e-02  5.50063327e-04 -1.51140150e-02 -7.53476331e-03
  3.88254933e-02  6.68118745e-02  9.04517807e-03 -8.00907798e-03
  2.76744049e-02 -3.36129474e-03 -3.67533043e-02  2.55681239e-02
  3.40631790e-02 -4.09387723e-02 -2.58145723e-02  2.31654737e-02
  1.16293877e-01  2.15445738e-02 -2.14575268e-02 -7.90842175e-02
 -1.44254218e-03 -1.52117927e-02 -6.23725764e-02  1.44038036e-01
 -4.03785110e-02 -8.19947794e-02  1.92157517e-03  7.18507497e-03
 -3.12223975e-02 -6.81799352e-02 -2.39071827e-02  7.22566899e-03
  1.10237688e-01 -2.65700258e-02 -3.74349877e-02  6.39888458e-03
 -1.09164968e-01  1.06028253e-02  5.81746958e-02  4.43062186e-02
 -1.35294184e-01 -3.21533270e-02 -9.38385874e-02 -3.55199873e-02
 -1.57530326e-02 -5.94779104e-02 -8.19859933e-03  1.11911185e-02
  2.24250499e-02 -1.98459486e-03 -7.83597119e-03  2.15797704e-02
 -1.17098980e-01  1.63545236e-02  7.12426659e-03  8.19452256e-02
  3.83530706e-02 -1.54824066e-03 -1.99557915e-02  1.05381474e-01
 -3.77897583e-02  8.36966783e-02  2.44509131e-02  3.44036482e-02
  2.41905469e-02 -4.00386471e-03 -4.81737331e-02  4.88992296e-02
  2.14359071e-02  2.23923922e-02 -5.71309105e-02 -4.45872388e-08
 -3.29199769e-02 -3.55868298e-03  4.77115251e-02  5.43723740e-02
  1.98434740e-02  9.84406751e-03 -4.42261286e-02  4.86806557e-02
 -1.23295402e-02  8.01506564e-02  4.53550220e-02 -9.64570232e-03
 -1.30134113e-02 -3.88759971e-02  4.00604820e-03  1.27741843e-01
  7.42083415e-02 -5.62172085e-02  2.12941617e-02 -7.85641652e-03
  6.03373162e-02 -4.54990081e-02 -4.93377820e-02  3.76714878e-02
  1.13609470e-02 -6.68480322e-02 -3.28016318e-02 -1.10788282e-03
 -7.09107518e-02  3.31799835e-02  1.64552424e-02 -4.84330989e-02
  5.36532477e-02 -5.88027462e-02  8.56882408e-02 -5.79874683e-03
  9.15560275e-02 -1.34028047e-01 -6.68818643e-03 -7.59536996e-02
 -2.03948878e-02  3.75315100e-02 -2.95802336e-02 -5.59549555e-02
  3.82575355e-02  3.12416349e-02 -4.75563556e-02 -6.13964871e-02
  5.06667346e-02 -2.40551829e-02 -3.06766126e-02 -2.36971732e-02
 -8.38488787e-02  4.26587015e-02  1.11349627e-01  5.74155264e-02
 -2.73206085e-02 -1.94094598e-03  4.04132120e-02  1.74163673e-02
 -4.34696786e-02  9.10701528e-02  2.53309645e-02 -1.57889798e-02]

In [24]:
from sentence_transformers import SentenceTransformer

models = [
    "all-MiniLM-L6-v2",
    "multi-qa-MiniLM-L6-cos-v1",
    "all-mpnet-base-v2"
]

sentences = [
    "What is Python programming?",
    "Explain machine learning"
]

for m in models:
    print("\nTesting model:", m)
    
    model = SentenceTransformer(m)
    
    embeddings = model.encode(sentences)
    
    print("Embedding shape:", embeddings.shape)

Testing model: all-MiniLM-L6-v2

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Embedding shape: (2, 384)

Testing model: multi-qa-MiniLM-L6-cos-v1

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/multi-qa-MiniLM-L6-cos-v1
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Embedding shape: (2, 384)

Testing model: all-mpnet-base-v2

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Embedding shape: (2, 768)